package com.emojitexttools.emojitexttools.bootstrap;

import com.emojitexttools.emojitexttools.model.Blog;
import com.emojitexttools.emojitexttools.model.Emoji;
import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class DataHolder {
    public static List<Emoji> allEmojis = new ArrayList<>();
    public static List<Emoji> smilesAndPeople = new ArrayList<>();
    public static List<Emoji> animalsAndNature = new ArrayList<>();
    public static List<Emoji> foodAndDrink = new ArrayList<>();
    public static List<Emoji> travelAndPlaces = new ArrayList<>();
    public static List<Emoji> activities = new ArrayList<>();
    public static List<Emoji> objects = new ArrayList<>();
    public static List<Emoji> symbols = new ArrayList<>();
    public static List<Emoji> flags = new ArrayList<>();
    public static List<Blog> blogs = new ArrayList<>();


    @PostConstruct
    public void init(){
        smilesAndPeople.add(new Emoji("😀", "Grinning Face"));
        smilesAndPeople.add(new Emoji("😃", "Grinning Face with Big Eyes"));
        smilesAndPeople.add(new Emoji("😄", "Grinning Face with Smiling Eyes"));
        smilesAndPeople.add(new Emoji("😁", "Beaming Face with Smiling Eyes"));
        smilesAndPeople.add(new Emoji("😆", "Grinning Squinting Face"));
        smilesAndPeople.add(new Emoji("😅", "Grinning Face with Sweat"));
        smilesAndPeople.add(new Emoji("😂", "Face with Tears of Joy"));
        smilesAndPeople.add(new Emoji("🤣", "Rolling on the Floor Laughing"));
        smilesAndPeople.add(new Emoji("😊", "Smiling Face with Smiling Eyes"));
        smilesAndPeople.add(new Emoji("😇", "Smiling Face with Halo"));
        smilesAndPeople.add(new Emoji("🙂", "Slightly Smiling Face"));
        smilesAndPeople.add(new Emoji("🙃", "Upside-Down Face"));
        smilesAndPeople.add(new Emoji("😉", "Winking Face"));
        smilesAndPeople.add(new Emoji("😌", "Relieved Face"));
        smilesAndPeople.add(new Emoji("😍", "Smiling Face with Heart-Eyes"));
        smilesAndPeople.add(new Emoji("🥰", "Smiling Face with Hearts"));
        smilesAndPeople.add(new Emoji("😘", "Face Blowing a Kiss"));
        smilesAndPeople.add(new Emoji("😗", "Kissing Face"));
        smilesAndPeople.add(new Emoji("😙", "Kissing Face with Smiling Eyes"));
        smilesAndPeople.add(new Emoji("😚", "Kissing Face with Closed Eyes"));
        smilesAndPeople.add(new Emoji("😋", "Face Savoring Food"));
        smilesAndPeople.add(new Emoji("😛", "Face with Tongue"));
        smilesAndPeople.add(new Emoji("😝", "Squinting Face with Tongue"));
        smilesAndPeople.add(new Emoji("😜", "Winking Face with Tongue"));
        smilesAndPeople.add(new Emoji("🤪", "Zany Face"));
        smilesAndPeople.add(new Emoji("🤨", "Face with Raised Eyebrow"));
        smilesAndPeople.add(new Emoji("🧐", "Face with Monocle"));
        smilesAndPeople.add(new Emoji("🤓", "Nerd Face"));
        smilesAndPeople.add(new Emoji("😎", "Smiling Face with Sunglasses"));
        smilesAndPeople.add(new Emoji("🥸", "Disguised Face"));
        smilesAndPeople.add(new Emoji("🤩", "Star-Struck"));
        smilesAndPeople.add(new Emoji("🥳", "Partying Face"));
        smilesAndPeople.add(new Emoji("😏", "Smirking Face"));
        smilesAndPeople.add(new Emoji("😒", "Unamused Face"));
        smilesAndPeople.add(new Emoji("😞", "Disappointed Face"));
        smilesAndPeople.add(new Emoji("😔", "Pensive Face"));
        smilesAndPeople.add(new Emoji("😟", "Worried Face"));
        smilesAndPeople.add(new Emoji("😕", "Confused Face"));
        smilesAndPeople.add(new Emoji("🙁", "Slightly Frowning Face"));
        smilesAndPeople.add(new Emoji("☹️", "Frowning Face"));
        smilesAndPeople.add(new Emoji("😣", "Persevering Face"));
        smilesAndPeople.add(new Emoji("😖", "Confounded Face"));
        smilesAndPeople.add(new Emoji("😫", "Tired Face"));
        smilesAndPeople.add(new Emoji("😩", "Weary Face"));
        smilesAndPeople.add(new Emoji("🥺", "Pleading Face"));
        smilesAndPeople.add(new Emoji("😢", "Crying Face"));
        smilesAndPeople.add(new Emoji("😭", "Loudly Crying Face"));
        smilesAndPeople.add(new Emoji("😤", "Face with Steam from Nose"));
        smilesAndPeople.add(new Emoji("😠", "Angry Face"));
        smilesAndPeople.add(new Emoji("😡", "Pouting Face"));
        smilesAndPeople.add(new Emoji("🤬", "Face with Symbols on Mouth"));
        smilesAndPeople.add(new Emoji("🤯", "Exploding Head"));
        smilesAndPeople.add(new Emoji("😳", "Flushed Face"));
        smilesAndPeople.add(new Emoji("🥵", "Hot Face"));
        smilesAndPeople.add(new Emoji("🥶", "Cold Face"));
        smilesAndPeople.add(new Emoji("😱", "Face Screaming in Fear"));
        smilesAndPeople.add(new Emoji("😨", "Fearful Face"));
        smilesAndPeople.add(new Emoji("😰", "Anxious Face with Sweat"));
        smilesAndPeople.add(new Emoji("😥", "Sad but Relieved Face"));
        smilesAndPeople.add(new Emoji("😓", "Downcast Face with Sweat"));
        smilesAndPeople.add(new Emoji("🤗", "Hugging Face"));
        smilesAndPeople.add(new Emoji("🤔", "Thinking Face"));
        smilesAndPeople.add(new Emoji("🤭", "Face with Hand Over Mouth"));
        smilesAndPeople.add(new Emoji("🤫", "Shushing Face"));
        smilesAndPeople.add(new Emoji("🤥", "Lying Face"));
        smilesAndPeople.add(new Emoji("😶", "Face Without Mouth"));
        smilesAndPeople.add(new Emoji("😐", "Neutral Face"));
        smilesAndPeople.add(new Emoji("😑", "Expressionless Face"));
        smilesAndPeople.add(new Emoji("😬", "Grimacing Face"));
        smilesAndPeople.add(new Emoji("🙄", "Face with Rolling Eyes"));
        smilesAndPeople.add(new Emoji("😯", "Hushed Face"));
        smilesAndPeople.add(new Emoji("😦", "Frowning Face with Open Mouth"));
        smilesAndPeople.add(new Emoji("😧", "Anguished Face"));
        smilesAndPeople.add(new Emoji("😮", "Face with Open Mouth"));
        smilesAndPeople.add(new Emoji("😲", "Astonished Face"));
        smilesAndPeople.add(new Emoji("🥱", "Yawning Face"));
        smilesAndPeople.add(new Emoji("😴", "Sleeping Face"));
        smilesAndPeople.add(new Emoji("🤤", "Drooling Face"));
        smilesAndPeople.add(new Emoji("😪", "Sleepy Face"));
        smilesAndPeople.add(new Emoji("😵", "Dizzy Face"));
        smilesAndPeople.add(new Emoji("🤐", "Zipper-Mouth Face"));
        smilesAndPeople.add(new Emoji("🥴", "Woozy Face"));
        smilesAndPeople.add(new Emoji("🤢", "Nauseated Face"));
        smilesAndPeople.add(new Emoji("🤮", "Face Vomiting"));
        smilesAndPeople.add(new Emoji("🤧", "Sneezing Face"));
        smilesAndPeople.add(new Emoji("😷", "Face with Medical Mask"));
        smilesAndPeople.add(new Emoji("🤒", "Face with Thermometer"));
        smilesAndPeople.add(new Emoji("🤕", "Face with Head-Bandage"));
        smilesAndPeople.add(new Emoji("🤑", "Money-Mouth Face"));
        smilesAndPeople.add(new Emoji("🤠", "Cowboy Hat Face"));
        smilesAndPeople.add(new Emoji("😈", "Smiling Face with Horns"));
        smilesAndPeople.add(new Emoji("👿", "Angry Face with Horns"));
        smilesAndPeople.add(new Emoji("👹", "Ogre"));
        smilesAndPeople.add(new Emoji("👺", "Goblin"));
        smilesAndPeople.add(new Emoji("🤡", "Clown Face"));
        smilesAndPeople.add(new Emoji("💩", "Pile of Poo"));
        smilesAndPeople.add(new Emoji("👻", "Ghost"));
        smilesAndPeople.add(new Emoji("💀", "Skull"));
        smilesAndPeople.add(new Emoji("☠️", "Skull and Crossbones"));
        smilesAndPeople.add(new Emoji("👽", "Alien"));
        smilesAndPeople.add(new Emoji("👾", "Alien Monster"));
        smilesAndPeople.add(new Emoji("🤖", "Robot"));
        smilesAndPeople.add(new Emoji("🎃", "Jack-O-Lantern"));
        smilesAndPeople.add(new Emoji("😺", "Grinning Cat"));
        smilesAndPeople.add(new Emoji("😸", "Grinning Cat with Smiling Eyes"));
        smilesAndPeople.add(new Emoji("😹", "Cat with Tears of Joy"));
        smilesAndPeople.add(new Emoji("😻", "Smiling Cat with Heart-Eyes"));
        smilesAndPeople.add(new Emoji("😼", "Cat with Wry Smile"));
        smilesAndPeople.add(new Emoji("😽", "Kissing Cat"));
        smilesAndPeople.add(new Emoji("🙀", "Weary Cat"));
        smilesAndPeople.add(new Emoji("😿", "Crying Cat"));
        smilesAndPeople.add(new Emoji("😾", "Pouting Cat"));
        smilesAndPeople.add(new Emoji("🙌", "Raising Hands"));
        smilesAndPeople.add(new Emoji("👏", "Clapping Hands"));
        smilesAndPeople.add(new Emoji("🙏", "Folded Hands"));
        smilesAndPeople.add(new Emoji("🤝", "Handshake"));
        smilesAndPeople.add(new Emoji("👍", "Thumbs Up"));
        smilesAndPeople.add(new Emoji("👎", "Thumbs Down"));
        smilesAndPeople.add(new Emoji("👊", "Oncoming Fist"));
        smilesAndPeople.add(new Emoji("✊", "Raised Fist"));
        smilesAndPeople.add(new Emoji("🤛", "Left-Facing Fist"));
        smilesAndPeople.add(new Emoji("🤜", "Right-Facing Fist"));
        smilesAndPeople.add(new Emoji("🤚", "Raised Back of Hand"));
        smilesAndPeople.add(new Emoji("🖐️", "Hand with Fingers Splayed"));
        smilesAndPeople.add(new Emoji("✋", "Raised Hand"));
        smilesAndPeople.add(new Emoji("🖖", "Vulcan Salute"));
        smilesAndPeople.add(new Emoji("👌", "OK Hand"));
        smilesAndPeople.add(new Emoji("🤌", "Pinched Fingers"));
        smilesAndPeople.add(new Emoji("🤏", "Pinching Hand"));
        smilesAndPeople.add(new Emoji("✌️", "Victory Hand"));
        smilesAndPeople.add(new Emoji("🤞", "Crossed Fingers"));
        smilesAndPeople.add(new Emoji("🤟", "Love-You Gesture"));
        smilesAndPeople.add(new Emoji("🤘", "Sign of the Horns"));
        smilesAndPeople.add(new Emoji("🤙", "Call Me Hand"));
        smilesAndPeople.add(new Emoji("👈", "Backhand Index Pointing Left"));
        smilesAndPeople.add(new Emoji("👉", "Backhand Index Pointing Right"));
        smilesAndPeople.add(new Emoji("👆", "Backhand Index Pointing Up"));
        smilesAndPeople.add(new Emoji("🖕", "Middle Finger"));
        smilesAndPeople.add(new Emoji("👇", "Backhand Index Pointing Down"));
        smilesAndPeople.add(new Emoji("☝️", "Index Pointing Up"));
        smilesAndPeople.add(new Emoji("✍️", "Writing Hand"));
        smilesAndPeople.add(new Emoji("🤳", "Selfie"));
        smilesAndPeople.add(new Emoji("💪", "Flexed Biceps"));
        smilesAndPeople.add(new Emoji("🦾", "Mechanical Arm"));
        smilesAndPeople.add(new Emoji("🦵", "Leg"));
        smilesAndPeople.add(new Emoji("🦿", "Mechanical Leg"));
        smilesAndPeople.add(new Emoji("🦶", "Foot"));
        smilesAndPeople.add(new Emoji("👂", "Ear"));
        smilesAndPeople.add(new Emoji("🦻", "Ear with Hearing Aid"));
        smilesAndPeople.add(new Emoji("👃", "Nose"));
        smilesAndPeople.add(new Emoji("🧠", "Brain"));
        smilesAndPeople.add(new Emoji("🫀", "Anatomical Heart"));
        smilesAndPeople.add(new Emoji("🫁", "Lungs"));
        smilesAndPeople.add(new Emoji("🦷", "Tooth"));
        smilesAndPeople.add(new Emoji("🦴", "Bone"));
        smilesAndPeople.add(new Emoji("👀", "Eyes"));
        smilesAndPeople.add(new Emoji("👁️", "Eye"));
        smilesAndPeople.add(new Emoji("👅", "Tongue"));
        smilesAndPeople.add(new Emoji("👄", "Mouth"));
        smilesAndPeople.add(new Emoji("💋", "Kiss Mark"));
        smilesAndPeople.add(new Emoji("🩸", "Drop of Blood"));
        smilesAndPeople.add(new Emoji("👶", "Baby"));
        smilesAndPeople.add(new Emoji("🧒", "Child"));
        smilesAndPeople.add(new Emoji("👦", "Boy"));
        smilesAndPeople.add(new Emoji("👧", "Girl"));
        smilesAndPeople.add(new Emoji("🧑", "Person"));
        smilesAndPeople.add(new Emoji("👱‍♂️", "Man with Blond Hair"));
        smilesAndPeople.add(new Emoji("👱‍♀️", "Woman with Blond Hair"));
        smilesAndPeople.add(new Emoji("👨", "Man"));
        smilesAndPeople.add(new Emoji("👩", "Woman"));
        smilesAndPeople.add(new Emoji("🧔", "Bearded Person"));
        smilesAndPeople.add(new Emoji("👵", "Old Woman"));
        smilesAndPeople.add(new Emoji("👴", "Old Man"));
        smilesAndPeople.add(new Emoji("🧓", "Older Person"));
        smilesAndPeople.add(new Emoji("👲", "Person with Skullcap"));
        smilesAndPeople.add(new Emoji("👳‍♂️", "Man Wearing Turban"));
        smilesAndPeople.add(new Emoji("👳‍♀️", "Woman Wearing Turban"));
        smilesAndPeople.add(new Emoji("🧕", "Woman with Headscarf"));
        smilesAndPeople.add(new Emoji("👮‍♂️", "Man Police Officer"));
        smilesAndPeople.add(new Emoji("👮‍♀️", "Woman Police Officer"));
        smilesAndPeople.add(new Emoji("👷‍♂️", "Man Construction Worker"));
        smilesAndPeople.add(new Emoji("👷‍♀️", "Woman Construction Worker"));
        smilesAndPeople.add(new Emoji("💂‍♂️", "Man Guard"));
        smilesAndPeople.add(new Emoji("💂‍♀️", "Woman Guard"));
        smilesAndPeople.add(new Emoji("🕵️‍♂️", "Man Detective"));
        smilesAndPeople.add(new Emoji("🕵️‍♀️", "Woman Detective"));
        smilesAndPeople.add(new Emoji("👩‍⚕️", "Woman Health Worker"));
        smilesAndPeople.add(new Emoji("👨‍⚕️", "Man Health Worker"));
        smilesAndPeople.add(new Emoji("👩‍🌾", "Woman Farmer"));
        smilesAndPeople.add(new Emoji("👨‍🌾", "Man Farmer"));
        smilesAndPeople.add(new Emoji("👩‍🍳", "Woman Cook"));
        smilesAndPeople.add(new Emoji("👨‍🍳", "Man Cook"));
        smilesAndPeople.add(new Emoji("👩‍🎓", "Woman Student"));
        smilesAndPeople.add(new Emoji("👨‍🎓", "Man Student"));
        smilesAndPeople.add(new Emoji("👩‍🏫", "Woman Teacher"));
        smilesAndPeople.add(new Emoji("👨‍🏫", "Man Teacher"));
        smilesAndPeople.add(new Emoji("👩‍🏭", "Woman Factory Worker"));
        smilesAndPeople.add(new Emoji("👨‍🏭", "Man Factory Worker"));
        smilesAndPeople.add(new Emoji("👩‍💻", "Woman Technologist"));
        smilesAndPeople.add(new Emoji("👨‍💻", "Man Technologist"));
        smilesAndPeople.add(new Emoji("👩‍🎨", "Woman Artist"));
        smilesAndPeople.add(new Emoji("👨‍🎨", "Man Artist"));
        smilesAndPeople.add(new Emoji("👩‍✈️", "Woman Pilot"));
        smilesAndPeople.add(new Emoji("👨‍✈️", "Man Pilot"));
        smilesAndPeople.add(new Emoji("👩‍🚀", "Woman Astronaut"));
        smilesAndPeople.add(new Emoji("👨‍🚀", "Man Astronaut"));
        smilesAndPeople.add(new Emoji("👩‍🚒", "Woman Firefighter"));
        smilesAndPeople.add(new Emoji("👨‍🚒", "Man Firefighter"));
        smilesAndPeople.add(new Emoji("🤶", "Mrs. Claus"));
        smilesAndPeople.add(new Emoji("🎅", "Santa Claus"));
        smilesAndPeople.add(new Emoji("🧑‍🎄", "Mx Claus"));
        smilesAndPeople.add(new Emoji("🦸‍♀️", "Woman Superhero"));
        smilesAndPeople.add(new Emoji("🦸‍♂️", "Man Superhero"));
        smilesAndPeople.add(new Emoji("🦹‍♀️", "Woman Supervillain"));
        smilesAndPeople.add(new Emoji("🦹‍♂️", "Man Supervillain"));
        smilesAndPeople.add(new Emoji("🧙‍♀️", "Woman Mage"));
        smilesAndPeople.add(new Emoji("🧙‍♂️", "Man Mage"));
        smilesAndPeople.add(new Emoji("🧚‍♀️", "Woman Fairy"));
        smilesAndPeople.add(new Emoji("🧚‍♂️", "Man Fairy"));
        smilesAndPeople.add(new Emoji("🧛‍♀️", "Woman Vampire"));
        smilesAndPeople.add(new Emoji("🧛‍♂️", "Man Vampire"));
        smilesAndPeople.add(new Emoji("🧜‍♀️", "Mermaid"));
        smilesAndPeople.add(new Emoji("🧜‍♂️", "Merman"));
        smilesAndPeople.add(new Emoji("🧝‍♀️", "Woman Elf"));
        smilesAndPeople.add(new Emoji("🧝‍♂️", "Man Elf"));
        smilesAndPeople.add(new Emoji("🧞‍♀️", "Woman Genie"));
        smilesAndPeople.add(new Emoji("🧞‍♂️", "Man Genie"));
        smilesAndPeople.add(new Emoji("🧟‍♀️", "Woman Zombie"));
        smilesAndPeople.add(new Emoji("🧟‍♂️", "Man Zombie"));
        smilesAndPeople.add(new Emoji("💃", "Woman Dancing"));
        smilesAndPeople.add(new Emoji("🕺", "Man Dancing"));
        smilesAndPeople.add(new Emoji("🕴️", "Person in Suit Levitating"));
        smilesAndPeople.add(new Emoji("👯‍♀️", "Women with Bunny Ears"));
        smilesAndPeople.add(new Emoji("👯‍♂️", "Men with Bunny Ears"));
        smilesAndPeople.add(new Emoji("🧖‍♀️", "Woman in Steamy Room"));
        smilesAndPeople.add(new Emoji("🧖‍♂️", "Man in Steamy Room"));
        smilesAndPeople.add(new Emoji("🧘‍♀️", "Woman in Lotus Position"));
        smilesAndPeople.add(new Emoji("🧘‍♂️", "Man in Lotus Position"));

        // Animals
        animalsAndNature.add(new Emoji("🐶", "Dog Face"));
        animalsAndNature.add(new Emoji("🐱", "Cat Face"));
        animalsAndNature.add(new Emoji("🐭", "Mouse Face"));
        animalsAndNature.add(new Emoji("🐹", "Hamster Face"));
        animalsAndNature.add(new Emoji("🐰", "Rabbit Face"));
        animalsAndNature.add(new Emoji("🦊", "Fox Face"));
        animalsAndNature.add(new Emoji("🐻", "Bear Face"));
        animalsAndNature.add(new Emoji("🐼", "Panda Face"));
        animalsAndNature.add(new Emoji("🐨", "Koala"));
        animalsAndNature.add(new Emoji("🐯", "Tiger Face"));
        animalsAndNature.add(new Emoji("🦁", "Lion Face"));
        animalsAndNature.add(new Emoji("🐮", "Cow Face"));
        animalsAndNature.add(new Emoji("🐷", "Pig Face"));
        animalsAndNature.add(new Emoji("🐽", "Pig Nose"));
        animalsAndNature.add(new Emoji("🐸", "Frog Face"));
        animalsAndNature.add(new Emoji("🐵", "Monkey Face"));
        animalsAndNature.add(new Emoji("🙈", "See-No-Evil Monkey"));
        animalsAndNature.add(new Emoji("🙉", "Hear-No-Evil Monkey"));
        animalsAndNature.add(new Emoji("🙊", "Speak-No-Evil Monkey"));
        animalsAndNature.add(new Emoji("🐔", "Chicken"));
        animalsAndNature.add(new Emoji("🐧", "Penguin"));
        animalsAndNature.add(new Emoji("🐦", "Bird"));
        animalsAndNature.add(new Emoji("🐤", "Baby Chick"));
        animalsAndNature.add(new Emoji("🐣", "Hatching Chick"));
        animalsAndNature.add(new Emoji("🐥", "Front-Facing Baby Chick"));
        animalsAndNature.add(new Emoji("🦆", "Duck"));
        animalsAndNature.add(new Emoji("🦅", "Eagle"));
        animalsAndNature.add(new Emoji("🦉", "Owl"));
        animalsAndNature.add(new Emoji("🦇", "Bat"));
        animalsAndNature.add(new Emoji("🐺", "Wolf"));
        animalsAndNature.add(new Emoji("🐗", "Boar"));
        animalsAndNature.add(new Emoji("🐴", "Horse Face"));
        animalsAndNature.add(new Emoji("🦄", "Unicorn Face"));
        animalsAndNature.add(new Emoji("🐝", "Honeybee"));
        animalsAndNature.add(new Emoji("🐛", "Bug"));
        animalsAndNature.add(new Emoji("🦋", "Butterfly"));
        animalsAndNature.add(new Emoji("🐌", "Snail"));
        animalsAndNature.add(new Emoji("🐞", "Lady Beetle"));
        animalsAndNature.add(new Emoji("🐜", "Ant"));
        animalsAndNature.add(new Emoji("🪲", "Beetle"));
        animalsAndNature.add(new Emoji("🐢", "Turtle"));
        animalsAndNature.add(new Emoji("🐍", "Snake"));
        animalsAndNature.add(new Emoji("🦎", "Lizard"));
        animalsAndNature.add(new Emoji("🦖", "T-Rex"));
        animalsAndNature.add(new Emoji("🦕", "Sauropod"));
        animalsAndNature.add(new Emoji("🐙", "Octopus"));
        animalsAndNature.add(new Emoji("🦑", "Squid"));
        animalsAndNature.add(new Emoji("🦐", "Shrimp"));
        animalsAndNature.add(new Emoji("🦞", "Lobster"));
        animalsAndNature.add(new Emoji("🦀", "Crab"));
        animalsAndNature.add(new Emoji("🐡", "Blowfish"));
        animalsAndNature.add(new Emoji("🐠", "Tropical Fish"));
        animalsAndNature.add(new Emoji("🐟", "Fish"));
        animalsAndNature.add(new Emoji("🐬", "Dolphin"));
        animalsAndNature.add(new Emoji("🐳", "Spouting Whale"));
        animalsAndNature.add(new Emoji("🐋", "Whale"));
        animalsAndNature.add(new Emoji("🦈", "Shark"));
        animalsAndNature.add(new Emoji("🐊", "Crocodile"));
        animalsAndNature.add(new Emoji("🐅", "Tiger"));
        animalsAndNature.add(new Emoji("🐆", "Leopard"));
        animalsAndNature.add(new Emoji("🦓", "Zebra"));
        animalsAndNature.add(new Emoji("🦍", "Gorilla"));
        animalsAndNature.add(new Emoji("🦧", "Orangutan"));
        animalsAndNature.add(new Emoji("🦣", "Mammoth"));
        animalsAndNature.add(new Emoji("🐘", "Elephant"));
        animalsAndNature.add(new Emoji("🦛", "Hippopotamus"));
        animalsAndNature.add(new Emoji("🦏", "Rhinoceros"));
        animalsAndNature.add(new Emoji("🐪", "Camel"));
        animalsAndNature.add(new Emoji("🐫", "Two-Hump Camel"));
        animalsAndNature.add(new Emoji("🦒", "Giraffe"));
        animalsAndNature.add(new Emoji("🦘", "Kangaroo"));
        animalsAndNature.add(new Emoji("🦥", "Sloth"));
        animalsAndNature.add(new Emoji("🦦", "Otter"));
        animalsAndNature.add(new Emoji("🦨", "Skunk"));
        animalsAndNature.add(new Emoji("🦡", "Badger"));
        animalsAndNature.add(new Emoji("🐿️", "Chipmunk"));
        animalsAndNature.add(new Emoji("🦔", "Hedgehog"));
        animalsAndNature.add(new Emoji("🦩", "Flamingo"));
        animalsAndNature.add(new Emoji("🕊️", "Dove"));
        animalsAndNature.add(new Emoji("🦜", "Parrot"));
        animalsAndNature.add(new Emoji("🦢", "Swan"));
        animalsAndNature.add(new Emoji("🦚", "Peacock"));
        animalsAndNature.add(new Emoji("🦤", "Dodo"));
        animalsAndNature.add(new Emoji("🪶", "Feather"));
        animalsAndNature.add(new Emoji("🪱", "Worm"));
        animalsAndNature.add(new Emoji("🐉", "Dragon"));
        animalsAndNature.add(new Emoji("🐲", "Dragon Face"));
        animalsAndNature.add(new Emoji("🌵", "Cactus"));
        animalsAndNature.add(new Emoji("🎄", "Christmas Tree"));
        animalsAndNature.add(new Emoji("🌲", "Evergreen Tree"));
        animalsAndNature.add(new Emoji("🌳", "Deciduous Tree"));
        animalsAndNature.add(new Emoji("🌴", "Palm Tree"));
        animalsAndNature.add(new Emoji("🌱", "Seedling"));
        animalsAndNature.add(new Emoji("🌿", "Herb"));
        animalsAndNature.add(new Emoji("☘️", "Shamrock"));
        animalsAndNature.add(new Emoji("🍀", "Four Leaf Clover"));
        animalsAndNature.add(new Emoji("🎍", "Pine Decoration"));
        animalsAndNature.add(new Emoji("🎋", "Tanabata Tree"));
        animalsAndNature.add(new Emoji("🍃", "Leaf Fluttering in Wind"));
        animalsAndNature.add(new Emoji("🍂", "Fallen Leaf"));
        animalsAndNature.add(new Emoji("🍁", "Maple Leaf"));
        animalsAndNature.add(new Emoji("🍄", "Mushroom"));
        animalsAndNature.add(new Emoji("🐚", "Spiral Shell"));
        animalsAndNature.add(new Emoji("💐", "Bouquet"));
        animalsAndNature.add(new Emoji("🌷", "Tulip"));
        animalsAndNature.add(new Emoji("🌹", "Rose"));
        animalsAndNature.add(new Emoji("🥀", "Wilted Flower"));
        animalsAndNature.add(new Emoji("🌺", "Hibiscus"));
        animalsAndNature.add(new Emoji("🌸", "Cherry Blossom"));
        animalsAndNature.add(new Emoji("🌼", "Blossom"));
        animalsAndNature.add(new Emoji("🌻", "Sunflower"));
        animalsAndNature.add(new Emoji("🌞", "Sun with Face"));
        animalsAndNature.add(new Emoji("🌝", "Full Moon with Face"));
        animalsAndNature.add(new Emoji("🌛", "First Quarter Moon with Face"));
        animalsAndNature.add(new Emoji("🌜", "Last Quarter Moon with Face"));
        animalsAndNature.add(new Emoji("🌚", "New Moon with Face"));
        animalsAndNature.add(new Emoji("🌕", "Full Moon"));
        animalsAndNature.add(new Emoji("🌖", "Waning Gibbous Moon"));
        animalsAndNature.add(new Emoji("🌗", "Last Quarter Moon"));
        animalsAndNature.add(new Emoji("🌘", "Waning Crescent Moon"));
        animalsAndNature.add(new Emoji("🌑", "New Moon"));
        animalsAndNature.add(new Emoji("🌒", "Waxing Crescent Moon"));
        animalsAndNature.add(new Emoji("🌓", "First Quarter Moon"));
        animalsAndNature.add(new Emoji("🌔", "Waxing Gibbous Moon"));
        animalsAndNature.add(new Emoji("🌙", "Crescent Moon"));
        animalsAndNature.add(new Emoji("🌎", "Globe Showing Americas"));
        animalsAndNature.add(new Emoji("🌍", "Globe Showing Europe-Africa"));
        animalsAndNature.add(new Emoji("🌏", "Globe Showing Asia-Australia"));
        animalsAndNature.add(new Emoji("💫", "Dizzy"));
        animalsAndNature.add(new Emoji("⭐", "Star"));
        animalsAndNature.add(new Emoji("🌟", "Glowing Star"));
        animalsAndNature.add(new Emoji("✨", "Sparkles"));
        animalsAndNature.add(new Emoji("⚡", "High Voltage"));
        animalsAndNature.add(new Emoji("☄️", "Comet"));
        animalsAndNature.add(new Emoji("🔥", "Fire"));
        animalsAndNature.add(new Emoji("💥", "Collision"));
        animalsAndNature.add(new Emoji("🌪️", "Tornado"));
        animalsAndNature.add(new Emoji("🌈", "Rainbow"));
        animalsAndNature.add(new Emoji("☀️", "Sun"));
        animalsAndNature.add(new Emoji("🌤️", "Sun Behind Small Cloud"));
        animalsAndNature.add(new Emoji("⛅", "Sun Behind Cloud"));
        animalsAndNature.add(new Emoji("🌥️", "Sun Behind Large Cloud"));
        animalsAndNature.add(new Emoji("🌦️", "Sun Behind Rain Cloud"));
        animalsAndNature.add(new Emoji("🌧️", "Cloud with Rain"));
        animalsAndNature.add(new Emoji("⛈️", "Cloud with Lightning and Rain"));
        animalsAndNature.add(new Emoji("🌩️", "Cloud with Lightning"));
        animalsAndNature.add(new Emoji("🌨️", "Cloud with Snow"));
        animalsAndNature.add(new Emoji("❄️", "Snowflake"));
        animalsAndNature.add(new Emoji("☃️", "Snowman"));
        animalsAndNature.add(new Emoji("⛄", "Snowman Without Snow"));
        animalsAndNature.add(new Emoji("🌬️", "Wind Face"));
        animalsAndNature.add(new Emoji("💨", "Dashing Away"));
        animalsAndNature.add(new Emoji("💧", "Droplet"));
        animalsAndNature.add(new Emoji("💦", "Sweat Droplets"));
        animalsAndNature.add(new Emoji("☔", "Umbrella with Rain Drops"));
        animalsAndNature.add(new Emoji("🌊", "Water Wave"));

        // Food & Drink
        foodAndDrink.add(new Emoji("🍏", "Green Apple"));
        foodAndDrink.add(new Emoji("🍎", "Red Apple"));
        foodAndDrink.add(new Emoji("🍐", "Pear"));
        foodAndDrink.add(new Emoji("🍊", "Tangerine"));
        foodAndDrink.add(new Emoji("🍋", "Lemon"));
        foodAndDrink.add(new Emoji("🍌", "Banana"));
        foodAndDrink.add(new Emoji("🍉", "Watermelon"));
        foodAndDrink.add(new Emoji("🍇", "Grapes"));
        foodAndDrink.add(new Emoji("🍓", "Strawberry"));
        foodAndDrink.add(new Emoji("🫐", "Blueberries"));
        foodAndDrink.add(new Emoji("🍈", "Melon"));
        foodAndDrink.add(new Emoji("🍒", "Cherries"));
        foodAndDrink.add(new Emoji("🍑", "Peach"));
        foodAndDrink.add(new Emoji("🥭", "Mango"));
        foodAndDrink.add(new Emoji("🍍", "Pineapple"));
        foodAndDrink.add(new Emoji("🥥", "Coconut"));
        foodAndDrink.add(new Emoji("🥝", "Kiwi Fruit"));
        foodAndDrink.add(new Emoji("🍅", "Tomato"));
        foodAndDrink.add(new Emoji("🍆", "Eggplant"));
        foodAndDrink.add(new Emoji("🥑", "Avocado"));
        foodAndDrink.add(new Emoji("🥦", "Broccoli"));
        foodAndDrink.add(new Emoji("🥬", "Leafy Green"));
        foodAndDrink.add(new Emoji("🥒", "Cucumber"));
        foodAndDrink.add(new Emoji("🌶️", "Hot Pepper"));
        foodAndDrink.add(new Emoji("🫑", "Bell Pepper"));
        foodAndDrink.add(new Emoji("🌽", "Ear of Corn"));
        foodAndDrink.add(new Emoji("🥕", "Carrot"));
        foodAndDrink.add(new Emoji("🫒", "Olive"));
        foodAndDrink.add(new Emoji("🥔", "Potato"));
        foodAndDrink.add(new Emoji("🍠", "Roasted Sweet Potato"));
        foodAndDrink.add(new Emoji("🥐", "Croissant"));
        foodAndDrink.add(new Emoji("🥯", "Bagel"));
        foodAndDrink.add(new Emoji("🍞", "Bread"));
        foodAndDrink.add(new Emoji("🥖", "Baguette Bread"));
        foodAndDrink.add(new Emoji("🥨", "Pretzel"));
        foodAndDrink.add(new Emoji("🥞", "Pancakes"));
        foodAndDrink.add(new Emoji("🧇", "Waffle"));
        foodAndDrink.add(new Emoji("🧀", "Cheese Wedge"));
        foodAndDrink.add(new Emoji("🍖", "Meat on Bone"));
        foodAndDrink.add(new Emoji("🍗", "Poultry Leg"));
        foodAndDrink.add(new Emoji("🥩", "Cut of Meat"));
        foodAndDrink.add(new Emoji("🥓", "Bacon"));
        foodAndDrink.add(new Emoji("🍔", "Hamburger"));
        foodAndDrink.add(new Emoji("🍟", "French Fries"));
        foodAndDrink.add(new Emoji("🍕", "Pizza"));
        foodAndDrink.add(new Emoji("🌭", "Hot Dog"));
        foodAndDrink.add(new Emoji("🥪", "Sandwich"));
        foodAndDrink.add(new Emoji("🌮", "Taco"));
        foodAndDrink.add(new Emoji("🌯", "Burrito"));
        foodAndDrink.add(new Emoji("🫔", "Tamale"));
        foodAndDrink.add(new Emoji("🥗", "Green Salad"));
        foodAndDrink.add(new Emoji("🥘", "Shallow Pan of Food"));
        foodAndDrink.add(new Emoji("🫕", "Fondue"));
        foodAndDrink.add(new Emoji("🥫", "Canned Food"));
        foodAndDrink.add(new Emoji("🍝", "Spaghetti"));
        foodAndDrink.add(new Emoji("🍜", "Steaming Bowl"));
        foodAndDrink.add(new Emoji("🍲", "Pot of Food"));
        foodAndDrink.add(new Emoji("🍛", "Curry Rice"));
        foodAndDrink.add(new Emoji("🍣", "Sushi"));
        foodAndDrink.add(new Emoji("🍱", "Bento Box"));
        foodAndDrink.add(new Emoji("🥟", "Dumpling"));
        foodAndDrink.add(new Emoji("🦪", "Oyster"));
        foodAndDrink.add(new Emoji("🍤", "Fried Shrimp"));
        foodAndDrink.add(new Emoji("🍙", "Rice Ball"));
        foodAndDrink.add(new Emoji("🍚", "Cooked Rice"));
        foodAndDrink.add(new Emoji("🍘", "Rice Cracker"));
        foodAndDrink.add(new Emoji("🍥", "Fish Cake with Swirl"));
        foodAndDrink.add(new Emoji("🥠", "Fortune Cookie"));
        foodAndDrink.add(new Emoji("🥡", "Takeout Box"));
        foodAndDrink.add(new Emoji("🍢", "Oden"));
        foodAndDrink.add(new Emoji("🍡", "Dango"));
        foodAndDrink.add(new Emoji("🥧", "Pie"));
        foodAndDrink.add(new Emoji("🍰", "Shortcake"));
        foodAndDrink.add(new Emoji("🎂", "Birthday Cake"));
        foodAndDrink.add(new Emoji("🧁", "Cupcake"));
        foodAndDrink.add(new Emoji("🍮", "Custard"));
        foodAndDrink.add(new Emoji("🍭", "Lollipop"));
        foodAndDrink.add(new Emoji("🍬", "Candy"));
        foodAndDrink.add(new Emoji("🍫", "Chocolate Bar"));
        foodAndDrink.add(new Emoji("🍿", "Popcorn"));
        foodAndDrink.add(new Emoji("🧂", "Salt"));
        foodAndDrink.add(new Emoji("🥤", "Cup with Straw"));
        foodAndDrink.add(new Emoji("🧃", "Beverage Box"));
        foodAndDrink.add(new Emoji("🧉", "Mate"));
        foodAndDrink.add(new Emoji("🫖", "Teapot"));
        foodAndDrink.add(new Emoji("☕", "Hot Beverage"));
        foodAndDrink.add(new Emoji("🍵", "Teacup Without Handle"));
        foodAndDrink.add(new Emoji("🧋", "Bubble Tea"));
        foodAndDrink.add(new Emoji("🍶", "Sake"));
        foodAndDrink.add(new Emoji("🍺", "Beer Mug"));
        foodAndDrink.add(new Emoji("🍻", "Clinking Beer Mugs"));
        foodAndDrink.add(new Emoji("🥂", "Clinking Glasses"));
        foodAndDrink.add(new Emoji("🍷", "Wine Glass"));
        foodAndDrink.add(new Emoji("🥃", "Tumbler Glass"));
        foodAndDrink.add(new Emoji("🍸", "Cocktail Glass"));
        foodAndDrink.add(new Emoji("🍹", "Tropical Drink"));
        foodAndDrink.add(new Emoji("🍾", "Bottle with Popping Cork"));
        foodAndDrink.add(new Emoji("🧊", "Ice"));

        // Travel & Places
        travelAndPlaces.add(new Emoji("🚗", "Car"));
        travelAndPlaces.add(new Emoji("🚕", "Taxi"));
        travelAndPlaces.add(new Emoji("🚙", "Sport Utility Vehicle"));
        travelAndPlaces.add(new Emoji("🚌", "Bus"));
        travelAndPlaces.add(new Emoji("🚎", "Trolleybus"));
        travelAndPlaces.add(new Emoji("🏎️", "Racing Car"));
        travelAndPlaces.add(new Emoji("🚓", "Police Car"));
        travelAndPlaces.add(new Emoji("🚑", "Ambulance"));
        travelAndPlaces.add(new Emoji("🚒", "Fire Engine"));
        travelAndPlaces.add(new Emoji("🚐", "Minibus"));
        travelAndPlaces.add(new Emoji("🛻", "Pickup Truck"));
        travelAndPlaces.add(new Emoji("🚚", "Delivery Truck"));
        travelAndPlaces.add(new Emoji("🚛", "Articulated Lorry"));
        travelAndPlaces.add(new Emoji("🚜", "Tractor"));
        travelAndPlaces.add(new Emoji("🛵", "Motor Scooter"));
        travelAndPlaces.add(new Emoji("🏍️", "Motorcycle"));
        travelAndPlaces.add(new Emoji("🛺", "Auto Rickshaw"));
        travelAndPlaces.add(new Emoji("🚲", "Bicycle"));
        travelAndPlaces.add(new Emoji("🛴", "Kick Scooter"));
        travelAndPlaces.add(new Emoji("🛹", "Skateboard"));
        travelAndPlaces.add(new Emoji("🚏", "Bus Stop"));
        travelAndPlaces.add(new Emoji("🛣️", "Motorway"));
        travelAndPlaces.add(new Emoji("🛤️", "Railway Track"));
        travelAndPlaces.add(new Emoji("⛽", "Fuel Pump"));
        travelAndPlaces.add(new Emoji("🚨", "Police Light"));
        travelAndPlaces.add(new Emoji("🚥", "Horizontal Traffic Light"));
        travelAndPlaces.add(new Emoji("🚦", "Vertical Traffic Light"));
        travelAndPlaces.add(new Emoji("🛑", "Stop Sign"));
        travelAndPlaces.add(new Emoji("🚧", "Construction"));
        travelAndPlaces.add(new Emoji("⚓", "Anchor"));
        travelAndPlaces.add(new Emoji("⛵", "Sailboat"));
        travelAndPlaces.add(new Emoji("🛶", "Canoe"));
        travelAndPlaces.add(new Emoji("🚤", "Speedboat"));
        travelAndPlaces.add(new Emoji("🛳️", "Passenger Ship"));
        travelAndPlaces.add(new Emoji("⛴️", "Ferry"));
        travelAndPlaces.add(new Emoji("🛥️", "Motor Boat"));
        travelAndPlaces.add(new Emoji("🚢", "Ship"));
        travelAndPlaces.add(new Emoji("✈️", "Airplane"));
        travelAndPlaces.add(new Emoji("🛫", "Airplane Departure"));
        travelAndPlaces.add(new Emoji("🛬", "Airplane Arrival"));
        travelAndPlaces.add(new Emoji("🪂", "Parachute"));
        travelAndPlaces.add(new Emoji("💺", "Seat"));
        travelAndPlaces.add(new Emoji("🚁", "Helicopter"));
        travelAndPlaces.add(new Emoji("🛩️", "Small Airplane"));
        travelAndPlaces.add(new Emoji("🛰️", "Satellite"));
        travelAndPlaces.add(new Emoji("🚀", "Rocket"));
        travelAndPlaces.add(new Emoji("🛸", "Flying Saucer"));
        travelAndPlaces.add(new Emoji("🏠", "House"));
        travelAndPlaces.add(new Emoji("🏡", "House with Garden"));
        travelAndPlaces.add(new Emoji("🏘️", "Houses"));
        travelAndPlaces.add(new Emoji("🏚️", "Derelict House"));
        travelAndPlaces.add(new Emoji("🏢", "Office Building"));
        travelAndPlaces.add(new Emoji("🏬", "Department Store"));
        travelAndPlaces.add(new Emoji("🏣", "Japanese Post Office"));
        travelAndPlaces.add(new Emoji("🏤", "Post Office"));
        travelAndPlaces.add(new Emoji("🏥", "Hospital"));
        travelAndPlaces.add(new Emoji("🏦", "Bank"));
        travelAndPlaces.add(new Emoji("🏨", "Hotel"));
        travelAndPlaces.add(new Emoji("🏩", "Love Hotel"));
        travelAndPlaces.add(new Emoji("🏪", "Convenience Store"));
        travelAndPlaces.add(new Emoji("🏫", "School"));
        travelAndPlaces.add(new Emoji("🏭", "Factory"));
        travelAndPlaces.add(new Emoji("🏯", "Japanese Castle"));
        travelAndPlaces.add(new Emoji("🏰", "Castle"));
        travelAndPlaces.add(new Emoji("💒", "Wedding"));
        travelAndPlaces.add(new Emoji("🗼", "Tokyo Tower"));
        travelAndPlaces.add(new Emoji("🗽", "Statue of Liberty"));
        travelAndPlaces.add(new Emoji("⛪", "Church"));
        travelAndPlaces.add(new Emoji("🕌", "Mosque"));
        travelAndPlaces.add(new Emoji("🛕", "Hindu Temple"));
        travelAndPlaces.add(new Emoji("🕍", "Synagogue"));
        travelAndPlaces.add(new Emoji("⛩️", "Shinto Shrine"));
        travelAndPlaces.add(new Emoji("🕋", "Kaaba"));
        travelAndPlaces.add(new Emoji("⛲", "Fountain"));
        travelAndPlaces.add(new Emoji("⛺", "Tent"));
        travelAndPlaces.add(new Emoji("🌁", "Foggy"));
        travelAndPlaces.add(new Emoji("🌃", "Night with Stars"));
        travelAndPlaces.add(new Emoji("🏙️", "Cityscape"));
        travelAndPlaces.add(new Emoji("🌄", "Sunrise Over Mountains"));
        travelAndPlaces.add(new Emoji("🌅", "Sunrise"));
        travelAndPlaces.add(new Emoji("🌆", "Cityscape at Dusk"));
        travelAndPlaces.add(new Emoji("🌇", "Sunset"));
        travelAndPlaces.add(new Emoji("🌉", "Bridge at Night"));
        travelAndPlaces.add(new Emoji("♨️", "Hot Springs"));
        travelAndPlaces.add(new Emoji("🎠", "Carousel Horse"));
        travelAndPlaces.add(new Emoji("🎡", "Ferris Wheel"));
        travelAndPlaces.add(new Emoji("🎢", "Roller Coaster"));
        travelAndPlaces.add(new Emoji("💈", "Barber Pole"));
        travelAndPlaces.add(new Emoji("🎪", "Circus Tent"));
        travelAndPlaces.add(new Emoji("🗿", "Moai"));


        // Activities
        activities.add(new Emoji("⚽", "Soccer Ball"));
        activities.add(new Emoji("🏀", "Basketball"));
        activities.add(new Emoji("🏈", "American Football"));
        activities.add(new Emoji("⚾", "Baseball"));
        activities.add(new Emoji("🥎", "Softball"));
        activities.add(new Emoji("🎾", "Tennis"));
        activities.add(new Emoji("🏐", "Volleyball"));
        activities.add(new Emoji("🏉", "Rugby Football"));
        activities.add(new Emoji("🎱", "Billiards"));
        activities.add(new Emoji("🏓", "Table Tennis"));
        activities.add(new Emoji("🏸", "Badminton"));
        activities.add(new Emoji("🥅", "Goal Net"));
        activities.add(new Emoji("🏒", "Ice Hockey"));
        activities.add(new Emoji("🏑", "Field Hockey"));
        activities.add(new Emoji("🥍", "Lacrosse"));
        activities.add(new Emoji("🏏", "Cricket"));
        activities.add(new Emoji("⛳", "Flag in Hole"));
        activities.add(new Emoji("🏹", "Bow and Arrow"));
        activities.add(new Emoji("🎣", "Fishing Pole"));
        activities.add(new Emoji("🤿", "Diving Mask"));
        activities.add(new Emoji("🥊", "Boxing Glove"));
        activities.add(new Emoji("🥋", "Martial Arts Uniform"));
        activities.add(new Emoji("🎽", "Running Shirt"));
        activities.add(new Emoji("🛷", "Sled"));
        activities.add(new Emoji("⛸️", "Ice Skate"));
        activities.add(new Emoji("🥌", "Curling Stone"));
        activities.add(new Emoji("🛹", "Skateboard"));
        activities.add(new Emoji("🛼", "Roller Skate"));
        activities.add(new Emoji("🪁", "Kite"));
        activities.add(new Emoji("🎿", "Ski"));
        activities.add(new Emoji("🪂", "Parachute"));
        activities.add(new Emoji("🏂", "Snowboard"));
        activities.add(new Emoji("🏋️‍♂️", "Man Lifting Weights"));
        activities.add(new Emoji("🏋️‍♀️", "Woman Lifting Weights"));
        activities.add(new Emoji("🤸‍♂️", "Man Cartwheeling"));
        activities.add(new Emoji("🤸‍♀️", "Woman Cartwheeling"));
        activities.add(new Emoji("⛹️‍♂️", "Man Bouncing Ball"));
        activities.add(new Emoji("⛹️‍♀️", "Woman Bouncing Ball"));
        activities.add(new Emoji("🤾‍♂️", "Man Playing Handball"));
        activities.add(new Emoji("🤾‍♀️", "Woman Playing Handball"));
        activities.add(new Emoji("🏌️‍♂️", "Man Golfing"));
        activities.add(new Emoji("🏌️‍♀️", "Woman Golfing"));
        activities.add(new Emoji("🏄‍♂️", "Man Surfing"));
        activities.add(new Emoji("🏄‍♀️", "Woman Surfing"));
        activities.add(new Emoji("🏊‍♂️", "Man Swimming"));
        activities.add(new Emoji("🏊‍♀️", "Woman Swimming"));
        activities.add(new Emoji("🤽‍♂️", "Man Playing Water Polo"));
        activities.add(new Emoji("🤽‍♀️", "Woman Playing Water Polo"));
        activities.add(new Emoji("🚣‍♂️", "Man Rowing Boat"));
        activities.add(new Emoji("🚣‍♀️", "Woman Rowing Boat"));
        activities.add(new Emoji("🧗‍♂️", "Man Climbing"));
        activities.add(new Emoji("🧗‍♀️", "Woman Climbing"));
        activities.add(new Emoji("🚵‍♂️", "Man Mountain Biking"));
        activities.add(new Emoji("🚵‍♀️", "Woman Mountain Biking"));
        activities.add(new Emoji("🚴‍♂️", "Man Biking"));
        activities.add(new Emoji("🚴‍♀️", "Woman Biking"));
        activities.add(new Emoji("🤹‍♂️", "Man Juggling"));
        activities.add(new Emoji("🤹‍♀️", "Woman Juggling"));
        activities.add(new Emoji("🎯", "Direct Hit"));
        activities.add(new Emoji("🎮", "Video Game"));
        activities.add(new Emoji("🎰", "Slot Machine"));
        activities.add(new Emoji("🎲", "Game Die"));
        activities.add(new Emoji("🧩", "Puzzle Piece"));
        activities.add(new Emoji("🪀", "Yo-Yo"));
        activities.add(new Emoji("🪁", "Kite"));
        activities.add(new Emoji("🎳", "Bowling"));
        activities.add(new Emoji("🎤", "Microphone"));
        activities.add(new Emoji("🎧", "Headphone"));
        activities.add(new Emoji("🎼", "Musical Score"));
        activities.add(new Emoji("🥁", "Drum"));
        activities.add(new Emoji("🎷", "Saxophone"));
        activities.add(new Emoji("🎸", "Guitar"));
        activities.add(new Emoji("🎹", "Musical Keyboard"));
        activities.add(new Emoji("🎺", "Trumpet"));
        activities.add(new Emoji("🪕", "Banjo"));
        activities.add(new Emoji("🎻", "Violin"));
        activities.add(new Emoji("🎬", "Clapper Board"));
        activities.add(new Emoji("🎨", "Artist Palette"));
        activities.add(new Emoji("🎭", "Performing Arts"));
        activities.add(new Emoji("🎪", "Circus Tent"));
        activities.add(new Emoji("🎟️", "Admission Tickets"));
        activities.add(new Emoji("🎫", "Ticket"));

        // Objects
        objects.add(new Emoji("⌚", "Watch"));
        objects.add(new Emoji("📱", "Mobile Phone"));
        objects.add(new Emoji("💻", "Laptop"));
        objects.add(new Emoji("🖥️", "Desktop Computer"));
        objects.add(new Emoji("🖨️", "Printer"));
        objects.add(new Emoji("⌨️", "Keyboard"));
        objects.add(new Emoji("🖱️", "Computer Mouse"));
        objects.add(new Emoji("🖲️", "Trackball"));
        objects.add(new Emoji("💽", "Computer Disk"));
        objects.add(new Emoji("💾", "Floppy Disk"));
        objects.add(new Emoji("💿", "Optical Disk"));
        objects.add(new Emoji("📀", "DVD"));
        objects.add(new Emoji("📼", "Videotape"));
        objects.add(new Emoji("📷", "Camera"));
        objects.add(new Emoji("📸", "Camera with Flash"));
        objects.add(new Emoji("📹", "Video Camera"));
        objects.add(new Emoji("🎥", "Movie Camera"));
        objects.add(new Emoji("📽️", "Film Projector"));
        objects.add(new Emoji("🎞️", "Film Frames"));
        objects.add(new Emoji("📞", "Telephone Receiver"));
        objects.add(new Emoji("☎️", "Telephone"));
        objects.add(new Emoji("📟", "Pager"));
        objects.add(new Emoji("📠", "Fax Machine"));
        objects.add(new Emoji("📺", "Television"));
        objects.add(new Emoji("📻", "Radio"));
        objects.add(new Emoji("🎙️", "Studio Microphone"));
        objects.add(new Emoji("🎚️", "Level Slider"));
        objects.add(new Emoji("🎛️", "Control Knobs"));
        objects.add(new Emoji("⏱️", "Stopwatch"));
        objects.add(new Emoji("⏲️", "Timer Clock"));
        objects.add(new Emoji("⏰", "Alarm Clock"));
        objects.add(new Emoji("🕰️", "Mantelpiece Clock"));
        objects.add(new Emoji("⌛", "Hourglass Done"));
        objects.add(new Emoji("⏳", "Hourglass Not Done"));
        objects.add(new Emoji("📡", "Satellite Antenna"));
        objects.add(new Emoji("🔋", "Battery"));
        objects.add(new Emoji("🔌", "Electric Plug"));
        objects.add(new Emoji("💡", "Light Bulb"));
        objects.add(new Emoji("🔦", "Flashlight"));
        objects.add(new Emoji("🕯️", "Candle"));
        objects.add(new Emoji("🪔", "Diya Lamp"));
        objects.add(new Emoji("🧯", "Fire Extinguisher"));
        objects.add(new Emoji("🛢️", "Oil Drum"));
        objects.add(new Emoji("💸", "Money with Wings"));
        objects.add(new Emoji("💵", "Dollar Banknote"));
        objects.add(new Emoji("💴", "Yen Banknote"));
        objects.add(new Emoji("💶", "Euro Banknote"));
        objects.add(new Emoji("💷", "Pound Banknote"));
        objects.add(new Emoji("💰", "Money Bag"));
        objects.add(new Emoji("💳", "Credit Card"));
        objects.add(new Emoji("🧾", "Receipt"));
        objects.add(new Emoji("💎", "Gem Stone"));
        objects.add(new Emoji("⚖️", "Balance Scale"));
        objects.add(new Emoji("🔧", "Wrench"));
        objects.add(new Emoji("🪛", "Screwdriver"));
        objects.add(new Emoji("🔨", "Hammer"));
        objects.add(new Emoji("⛏️", "Pick"));
        objects.add(new Emoji("⚒️", "Hammer and Pick"));
        objects.add(new Emoji("🛠️", "Hammer and Wrench"));
        objects.add(new Emoji("🗡️", "Dagger"));
        objects.add(new Emoji("⚔️", "Crossed Swords"));
        objects.add(new Emoji("🔫", "Pistol"));
        objects.add(new Emoji("🏹", "Bow and Arrow"));
        objects.add(new Emoji("🛡️", "Shield"));
        objects.add(new Emoji("🚪", "Door"));
        objects.add(new Emoji("🪑", "Chair"));
        objects.add(new Emoji("🛋️", "Couch and Lamp"));
        objects.add(new Emoji("🛏️", "Bed"));
        objects.add(new Emoji("🛌", "Person in Bed"));
        objects.add(new Emoji("🪞", "Mirror"));
        objects.add(new Emoji("🪟", "Window"));
        objects.add(new Emoji("🛁", "Bathtub"));
        objects.add(new Emoji("🚿", "Shower"));
        objects.add(new Emoji("🪠", "Plunger"));
        objects.add(new Emoji("🚽", "Toilet"));
        objects.add(new Emoji("🪤", "Mouse Trap"));
        objects.add(new Emoji("🧴", "Lotion Bottle"));
        objects.add(new Emoji("🧷", "Safety Pin"));
        objects.add(new Emoji("🧹", "Broom"));
        objects.add(new Emoji("🧺", "Basket"));
        objects.add(new Emoji("🧻", "Toilet Paper"));
        objects.add(new Emoji("🪣", "Bucket"));
        objects.add(new Emoji("🧼", "Soap"));
        objects.add(new Emoji("🪥", "Toothbrush"));
        objects.add(new Emoji("🧽", "Sponge"));
        objects.add(new Emoji("🧯", "Fire Extinguisher"));
        objects.add(new Emoji("🛒", "Shopping Cart"));
        objects.add(new Emoji("🚬", "Cigarette"));
        objects.add(new Emoji("⚱️", "Funeral Urn"));
        objects.add(new Emoji("🗿", "Moai"));
        objects.add(new Emoji("🪑", "Chair"));
        objects.add(new Emoji("🛎️", "Bellhop Bell"));
        objects.add(new Emoji("🔑", "Key"));
        objects.add(new Emoji("🗝️", "Old Key"));
        objects.add(new Emoji("🚪", "Door"));
        objects.add(new Emoji("🛍️", "Shopping Bags"));
        objects.add(new Emoji("🎁", "Wrapped Gift"));
        objects.add(new Emoji("🎈", "Balloon"));
        objects.add(new Emoji("🎏", "Carp Streamer"));
        objects.add(new Emoji("🎀", "Ribbon"));
        objects.add(new Emoji("🪁", "Kite"));

        // Symbols
        symbols.add(new Emoji("💓", "Beating Heart"));
        symbols.add(new Emoji("💗", "Growing Heart"));
        symbols.add(new Emoji("💖", "Sparkling Heart"));
        symbols.add(new Emoji("💘", "Heart with Arrow"));
        symbols.add(new Emoji("💝", "Heart with Ribbon"));
        symbols.add(new Emoji("💟", "Heart Decoration"));
        symbols.add(new Emoji("☮️", "Peace Symbol"));
        symbols.add(new Emoji("✝️", "Latin Cross"));
        symbols.add(new Emoji("☪️", "Star and Crescent"));
        symbols.add(new Emoji("🕉️", "Om Symbol"));
        symbols.add(new Emoji("☸️", "Wheel of Dharma"));
        symbols.add(new Emoji("✡️", "Star of David"));
        symbols.add(new Emoji("🔯", "Six-Pointed Star with Middle Dot"));
        symbols.add(new Emoji("🕎", "Menorah"));
        symbols.add(new Emoji("☯️", "Yin Yang"));
        symbols.add(new Emoji("☦️", "Orthodox Cross"));
        symbols.add(new Emoji("🛐", "Place of Worship"));
        symbols.add(new Emoji("⛎", "Ophiuchus"));
        symbols.add(new Emoji("♈", "Aries"));
        symbols.add(new Emoji("♉", "Taurus"));
        symbols.add(new Emoji("♊", "Gemini"));
        symbols.add(new Emoji("♋", "Cancer"));
        symbols.add(new Emoji("♌", "Leo"));
        symbols.add(new Emoji("♍", "Virgo"));
        symbols.add(new Emoji("♎", "Libra"));
        symbols.add(new Emoji("♏", "Scorpio"));
        symbols.add(new Emoji("♐", "Sagittarius"));
        symbols.add(new Emoji("♑", "Capricorn"));
        symbols.add(new Emoji("♒", "Aquarius"));
        symbols.add(new Emoji("♓", "Pisces"));
        symbols.add(new Emoji("🆔", "ID Button"));
        symbols.add(new Emoji("⚛️", "Atom Symbol"));
        symbols.add(new Emoji("🈳", "Japanese Vacancy Button"));
        symbols.add(new Emoji("🈹", "Japanese Discount Button"));
        symbols.add(new Emoji("☢️", "Radioactive"));
        symbols.add(new Emoji("☣️", "Biohazard"));
        symbols.add(new Emoji("📴", "Mobile Phone Off"));
        symbols.add(new Emoji("📳", "Vibration Mode"));
        symbols.add(new Emoji("🈶", "Japanese “Have” Button"));
        symbols.add(new Emoji("🈚", "Japanese “Free of Charge” Button"));
        symbols.add(new Emoji("🈸", "Japanese “Application” Button"));
        symbols.add(new Emoji("🈺", "Japanese “Open for Business” Button"));
        symbols.add(new Emoji("🈷️", "Japanese “Monthly Amount” Button"));
        symbols.add(new Emoji("✴️", "Eight-Pointed Star"));
        symbols.add(new Emoji("🆚", "VS Button"));
        symbols.add(new Emoji("💮", "White Flower"));
        symbols.add(new Emoji("🉐", "Japanese “Bargain” Button"));
        symbols.add(new Emoji("🉑", "Japanese “Acceptable” Button"));
        symbols.add(new Emoji("㊗️", "Japanese “Congratulations” Button"));
        symbols.add(new Emoji("㊙️", "Japanese “Secret” Button"));
        symbols.add(new Emoji("🈴", "Japanese “Passing Grade” Button"));
        symbols.add(new Emoji("🈵", "Japanese “No Vacancy” Button"));
        symbols.add(new Emoji("🈲", "Japanese “Prohibited” Button"));
        symbols.add(new Emoji("🅰️", "A Button (Blood Type)"));
        symbols.add(new Emoji("🅱️", "B Button (Blood Type)"));
        symbols.add(new Emoji("🆎", "AB Button (Blood Type)"));
        symbols.add(new Emoji("🅾️", "O Button (Blood Type)"));
        symbols.add(new Emoji("🆑", "CL Button"));
        symbols.add(new Emoji("🆒", "COOL Button"));
        symbols.add(new Emoji("🆓", "FREE Button"));
        symbols.add(new Emoji("ℹ️", "Information"));
        symbols.add(new Emoji("Ⓜ️", "M Button"));
        symbols.add(new Emoji("🆕", "NEW Button"));
        symbols.add(new Emoji("🆖", "NG Button"));
        symbols.add(new Emoji("🅿️", "Parking"));
        symbols.add(new Emoji("🆗", "OK Button"));
        symbols.add(new Emoji("🆘", "SOS Button"));
        symbols.add(new Emoji("🆙", "UP! Button"));
        symbols.add(new Emoji("🈁", "Japanese “Here” Button"));
        symbols.add(new Emoji("⚠️", "Warning"));
        symbols.add(new Emoji("🚸", "Children Crossing"));
        symbols.add(new Emoji("⛔", "No Entry"));
        symbols.add(new Emoji("🚫", "Prohibited"));
        symbols.add(new Emoji("🚳", "No Bicycles"));
        symbols.add(new Emoji("🚭", "No Smoking"));
        symbols.add(new Emoji("🚯", "No Littering"));
        symbols.add(new Emoji("🚱", "Non-Potable Water"));
        symbols.add(new Emoji("🔞", "No One Under 18"));
        symbols.add(new Emoji("⬆️", "Up Arrow"));
        symbols.add(new Emoji("⬇️", "Down Arrow"));
        symbols.add(new Emoji("⬅️", "Left Arrow"));
        symbols.add(new Emoji("➡️", "Right Arrow"));
        symbols.add(new Emoji("↗️", "Up-Right Arrow"));
        symbols.add(new Emoji("↘️", "Down-Right Arrow"));
        symbols.add(new Emoji("↙️", "Down-Left Arrow"));
        symbols.add(new Emoji("↖️", "Up-Left Arrow"));
        symbols.add(new Emoji("↔️", "Left-Right Arrow"));
        symbols.add(new Emoji("↕️", "Up-Down Arrow"));
        symbols.add(new Emoji("🔃", "Clockwise Arrows"));
        symbols.add(new Emoji("🔄", "Anticlockwise Arrows"));
        symbols.add(new Emoji("🔙", "Back Arrow"));
        symbols.add(new Emoji("🔚", "End Arrow"));
        symbols.add(new Emoji("🔛", "On! Arrow"));
        symbols.add(new Emoji("🔝", "Top Arrow"));
        symbols.add(new Emoji("🔜", "Soon Arrow"));
        symbols.add(new Emoji("🛑", "Stop Sign"));
        symbols.add(new Emoji("⏸️", "Pause Button"));
        symbols.add(new Emoji("⏯️", "Play/Pause Button"));
        symbols.add(new Emoji("⏹️", "Stop Button"));
        symbols.add(new Emoji("⏺️", "Record Button"));
        symbols.add(new Emoji("⏭️", "Next Track Button"));
        symbols.add(new Emoji("⏮️", "Previous Track Button"));
        symbols.add(new Emoji("⏩", "Fast-Forward Button"));
        symbols.add(new Emoji("⏪", "Rewind Button"));
        symbols.add(new Emoji("🔀", "Shuffle Tracks Button"));
        symbols.add(new Emoji("🔁", "Repeat Button"));
        symbols.add(new Emoji("🔂", "Repeat Single Button"));
        symbols.add(new Emoji("▶️", "Play Button"));
        symbols.add(new Emoji("◀️", "Reverse Button"));
        symbols.add(new Emoji("🔼", "Upwards Button"));
        symbols.add(new Emoji("🔽", "Downwards Button"));
        symbols.add(new Emoji("↩️", "Right Arrow Curving Left"));
        symbols.add(new Emoji("↪️", "Left Arrow Curving Right"));
        symbols.add(new Emoji("❗", "Exclamation"));
        symbols.add(new Emoji("❕", "White Exclamation"));
        symbols.add(new Emoji("❓", "Question"));
        symbols.add(new Emoji("❔", "White Question"));
        symbols.add(new Emoji("‼️", "Double Exclamation"));
        symbols.add(new Emoji("⁉️", "Exclamation Question"));
        symbols.add(new Emoji("🔅", "Dim Button"));
        symbols.add(new Emoji("🔆", "Bright Button"));
        symbols.add(new Emoji("〽️", "Part Alternation Mark"));
        symbols.add(new Emoji("⚕️", "Medical Symbol"));
        symbols.add(new Emoji("♻️", "Recycling Symbol"));
        symbols.add(new Emoji("⚜️", "Fleur-de-lis"));
        symbols.add(new Emoji("🔱", "Trident Emblem"));
        symbols.add(new Emoji("📛", "Name Badge"));
        symbols.add(new Emoji("🔰", "Japanese Beginner"));
        symbols.add(new Emoji("⭕", "Heavy Large Circle"));
        symbols.add(new Emoji("✅", "Check Mark Button"));
        symbols.add(new Emoji("☑️", "Check Box with Check"));
        symbols.add(new Emoji("✔️", "Check Mark"));
        symbols.add(new Emoji("❌", "Cross Mark"));
        symbols.add(new Emoji("❎", "Cross Mark Button"));
        symbols.add(new Emoji("➕", "Plus"));
        symbols.add(new Emoji("➖", "Minus"));
        symbols.add(new Emoji("➗", "Division"));
        symbols.add(new Emoji("✖️", "Multiply"));
        symbols.add(new Emoji("💲", "Dollar Sign"));
        symbols.add(new Emoji("💱", "Currency Exchange"));
        symbols.add(new Emoji("™️", "Trade Mark"));
        symbols.add(new Emoji("©️", "Copyright"));
        symbols.add(new Emoji("®️", "Registered"));

        // Flags
        flags.add(new Emoji("🇦🇮", "Anguilla Flag"));
        flags.add(new Emoji("🇦🇶", "Antarctica Flag"));
        flags.add(new Emoji("🇦🇬", "Antigua & Barbuda Flag"));
        flags.add(new Emoji("🇦🇷", "Argentina Flag"));
        flags.add(new Emoji("🇦🇲", "Armenia Flag"));
        flags.add(new Emoji("🇦🇼", "Aruba Flag"));
        flags.add(new Emoji("🇦🇺", "Australia Flag"));
        flags.add(new Emoji("🇦🇹", "Austria Flag"));
        flags.add(new Emoji("🇦🇿", "Azerbaijan Flag"));
        flags.add(new Emoji("🇧🇸", "Bahamas Flag"));
        flags.add(new Emoji("🇧🇭", "Bahrain Flag"));
        flags.add(new Emoji("🇧🇩", "Bangladesh Flag"));
        flags.add(new Emoji("🇧🇧", "Barbados Flag"));
        flags.add(new Emoji("🇧🇾", "Belarus Flag"));
        flags.add(new Emoji("🇧🇪", "Belgium Flag"));
        flags.add(new Emoji("🇧🇿", "Belize Flag"));
        flags.add(new Emoji("🇧🇯", "Benin Flag"));
        flags.add(new Emoji("🇧🇲", "Bermuda Flag"));
        flags.add(new Emoji("🇧🇹", "Bhutan Flag"));
        flags.add(new Emoji("🇧🇴", "Bolivia Flag"));
        flags.add(new Emoji("🇧🇦", "Bosnia & Herzegovina Flag"));
        flags.add(new Emoji("🇧🇼", "Botswana Flag"));
        flags.add(new Emoji("🇧🇷", "Brazil Flag"));
        flags.add(new Emoji("🇧🇳", "Brunei Flag"));
        flags.add(new Emoji("🇧🇬", "Bulgaria Flag"));
        flags.add(new Emoji("🇧🇫", "Burkina Faso Flag"));
        flags.add(new Emoji("🇧🇮", "Burundi Flag"));
        flags.add(new Emoji("🇨🇻", "Cabo Verde Flag"));
        flags.add(new Emoji("🇰🇭", "Cambodia Flag"));
        flags.add(new Emoji("🇨🇲", "Cameroon Flag"));
        flags.add(new Emoji("🇨🇦", "Canada Flag"));
        flags.add(new Emoji("🇰🇾", "Cayman Islands Flag"));
        flags.add(new Emoji("🇨🇫", "Central African Republic Flag"));
        flags.add(new Emoji("🇹🇩", "Chad Flag"));
        flags.add(new Emoji("🇨🇱", "Chile Flag"));
        flags.add(new Emoji("🇨🇳", "China Flag"));
        flags.add(new Emoji("🇨🇴", "Colombia Flag"));
        flags.add(new Emoji("🇰🇲", "Comoros Flag"));
        flags.add(new Emoji("🇨🇬", "Congo - Brazzaville Flag"));
        flags.add(new Emoji("🇨🇩", "Congo - Kinshasa Flag"));
        flags.add(new Emoji("🇨🇰", "Cook Islands Flag"));
        flags.add(new Emoji("🇨🇷", "Costa Rica Flag"));
        flags.add(new Emoji("🇭🇷", "Croatia Flag"));
        flags.add(new Emoji("🇨🇺", "Cuba Flag"));
        flags.add(new Emoji("🇨🇼", "Curaçao Flag"));
        flags.add(new Emoji("🇨🇾", "Cyprus Flag"));
        flags.add(new Emoji("🇨🇿", "Czechia Flag"));
        flags.add(new Emoji("🇩🇰", "Denmark Flag"));
        flags.add(new Emoji("🇩🇯", "Djibouti Flag"));
        flags.add(new Emoji("🇩🇲", "Dominica Flag"));
        flags.add(new Emoji("🇩🇴", "Dominican Republic Flag"));
        flags.add(new Emoji("🇪🇨", "Ecuador Flag"));
        flags.add(new Emoji("🇪🇬", "Egypt Flag"));
        flags.add(new Emoji("🇸🇻", "El Salvador Flag"));
        flags.add(new Emoji("🇬🇶", "Equatorial Guinea Flag"));
        flags.add(new Emoji("🇪🇷", "Eritrea Flag"));
        flags.add(new Emoji("🇪🇪", "Estonia Flag"));
        flags.add(new Emoji("🇸🇿", "Eswatini Flag"));
        flags.add(new Emoji("🇪🇹", "Ethiopia Flag"));
        flags.add(new Emoji("🇫🇰", "Falkland Islands Flag"));
        flags.add(new Emoji("🇫🇴", "Faroe Islands Flag"));
        flags.add(new Emoji("🇫🇯", "Fiji Flag"));
        flags.add(new Emoji("🇫🇮", "Finland Flag"));
        flags.add(new Emoji("🇫🇷", "France Flag"));
        flags.add(new Emoji("🇬🇫", "French Guiana Flag"));
        flags.add(new Emoji("🇵🇫", "French Polynesia Flag"));
        flags.add(new Emoji("🇹🇫", "French Southern Territories Flag"));
        flags.add(new Emoji("🇬🇦", "Gabon Flag"));
        flags.add(new Emoji("🇬🇲", "Gambia Flag"));
        flags.add(new Emoji("🇬🇪", "Georgia Flag"));
        flags.add(new Emoji("🇩🇪", "Germany Flag"));
        flags.add(new Emoji("🇬🇭", "Ghana Flag"));
        flags.add(new Emoji("🇬🇮", "Gibraltar Flag"));
        flags.add(new Emoji("🇬🇷", "Greece Flag"));
        flags.add(new Emoji("🇬🇱", "Greenland Flag"));
        flags.add(new Emoji("🇬🇩", "Grenada Flag"));
        flags.add(new Emoji("🇬🇵", "Guadeloupe Flag"));
        flags.add(new Emoji("🇬🇺", "Guam Flag"));
        flags.add(new Emoji("🇬🇹", "Guatemala Flag"));
        flags.add(new Emoji("🇬🇬", "Guernsey Flag"));
        flags.add(new Emoji("🇬🇳", "Guinea Flag"));
        flags.add(new Emoji("🇬🇼", "Guinea-Bissau Flag"));
        flags.add(new Emoji("🇬🇾", "Guyana Flag"));
        flags.add(new Emoji("🇭🇹", "Haiti Flag"));
        flags.add(new Emoji("🇭🇳", "Honduras Flag"));
        flags.add(new Emoji("🇭🇰", "Hong Kong Flag"));
        flags.add(new Emoji("🇭🇺", "Hungary Flag"));
        flags.add(new Emoji("🇮🇸", "Iceland Flag"));
        flags.add(new Emoji("🇮🇳", "India Flag"));
        flags.add(new Emoji("🇮🇩", "Indonesia Flag"));
        flags.add(new Emoji("🇮🇷", "Iran Flag"));
        flags.add(new Emoji("🇮🇶", "Iraq Flag"));
        flags.add(new Emoji("🇮🇪", "Ireland Flag"));
        flags.add(new Emoji("🇮🇲", "Isle of Man Flag"));
        flags.add(new Emoji("🇮🇱", "Israel Flag"));
        flags.add(new Emoji("🇮🇹", "Italy Flag"));
        flags.add(new Emoji("🇨🇮", "Ivory Coast Flag"));
        flags.add(new Emoji("🇯🇲", "Jamaica Flag"));
        flags.add(new Emoji("🇯🇵", "Japan Flag"));
        flags.add(new Emoji("🇯🇪", "Jersey Flag"));
        flags.add(new Emoji("🇯🇴", "Jordan Flag"));
        flags.add(new Emoji("🇰🇿", "Kazakhstan Flag"));
        flags.add(new Emoji("🇰🇪", "Kenya Flag"));
        flags.add(new Emoji("🇰🇮", "Kiribati Flag"));
        flags.add(new Emoji("🇽🇰", "Kosovo Flag"));
        flags.add(new Emoji("🇰🇼", "Kuwait Flag"));
        flags.add(new Emoji("🇰🇬", "Kyrgyzstan Flag"));
        flags.add(new Emoji("🇱🇦", "Laos Flag"));
        flags.add(new Emoji("🇱🇻", "Latvia Flag"));
        flags.add(new Emoji("🇱🇧", "Lebanon Flag"));
        flags.add(new Emoji("🇱🇸", "Lesotho Flag"));
        flags.add(new Emoji("🇱🇷", "Liberia Flag"));
        flags.add(new Emoji("🇱🇾", "Libya Flag"));
        flags.add(new Emoji("🇱🇮", "Liechtenstein Flag"));
        flags.add(new Emoji("🇱🇹", "Lithuania Flag"));
        flags.add(new Emoji("🇱🇺", "Luxembourg Flag"));
        flags.add(new Emoji("🇲🇴", "Macau Flag"));
        flags.add(new Emoji("🇲🇰", "North Macedonia Flag"));
        flags.add(new Emoji("🇲🇬", "Madagascar Flag"));
        flags.add(new Emoji("🇲🇼", "Malawi Flag"));
        flags.add(new Emoji("🇲🇾", "Malaysia Flag"));
        flags.add(new Emoji("🇲🇻", "Maldives Flag"));
        flags.add(new Emoji("🇲🇱", "Mali Flag"));
        flags.add(new Emoji("🇲🇹", "Malta Flag"));
        flags.add(new Emoji("🇲🇭", "Marshall Islands Flag"));
        flags.add(new Emoji("🇲🇶", "Martinique Flag"));
        flags.add(new Emoji("🇲🇷", "Mauritania Flag"));
        flags.add(new Emoji("🇲🇺", "Mauritius Flag"));
        flags.add(new Emoji("🇾🇹", "Mayotte Flag"));
        flags.add(new Emoji("🇲🇽", "Mexico Flag"));
        flags.add(new Emoji("🇫🇲", "Micronesia Flag"));
        flags.add(new Emoji("🇲🇩", "Moldova Flag"));
        flags.add(new Emoji("🇲🇨", "Monaco Flag"));
        flags.add(new Emoji("🇲🇳", "Mongolia Flag"));
        flags.add(new Emoji("🇲🇪", "Montenegro Flag"));
        flags.add(new Emoji("🇲🇸", "Montserrat Flag"));
        flags.add(new Emoji("🇲🇦", "Morocco Flag"));
        flags.add(new Emoji("🇲🇿", "Mozambique Flag"));
        flags.add(new Emoji("🇲🇲", "Myanmar Flag"));
        flags.add(new Emoji("🇳🇦", "Namibia Flag"));
        flags.add(new Emoji("🇳🇷", "Nauru Flag"));
        flags.add(new Emoji("🇳🇵", "Nepal Flag"));
        flags.add(new Emoji("🇳🇱", "Netherlands Flag"));
        flags.add(new Emoji("🇳🇨", "New Caledonia Flag"));
        flags.add(new Emoji("🇳🇿", "New Zealand Flag"));
        flags.add(new Emoji("🇳🇮", "Nicaragua Flag"));
        flags.add(new Emoji("🇳🇪", "Niger Flag"));
        flags.add(new Emoji("🇳🇬", "Nigeria Flag"));
        flags.add(new Emoji("🇳🇺", "Niue Flag"));
        flags.add(new Emoji("🇳🇫", "Norfolk Island Flag"));
        flags.add(new Emoji("🇰🇵", "North Korea Flag"));
        flags.add(new Emoji("🇲🇵", "Northern Mariana Islands Flag"));
        flags.add(new Emoji("🇳🇴", "Norway Flag"));
        flags.add(new Emoji("🇴🇲", "Oman Flag"));
        flags.add(new Emoji("🇵🇰", "Pakistan Flag"));
        flags.add(new Emoji("🇵🇼", "Palau Flag"));
        flags.add(new Emoji("🇵🇸", "Palestinian Territories Flag"));
        flags.add(new Emoji("🇵🇦", "Panama Flag"));
        flags.add(new Emoji("🇵🇬", "Papua New Guinea Flag"));
        flags.add(new Emoji("🇵🇾", "Paraguay Flag"));
        flags.add(new Emoji("🇵🇪", "Peru Flag"));
        flags.add(new Emoji("🇵🇭", "Philippines Flag"));
        flags.add(new Emoji("🇵🇳", "Pitcairn Islands Flag"));
        flags.add(new Emoji("🇵🇱", "Poland Flag"));
        flags.add(new Emoji("🇵🇹", "Portugal Flag"));
        flags.add(new Emoji("🇵🇷", "Puerto Rico Flag"));
        flags.add(new Emoji("🇶🇦", "Qatar Flag"));
        flags.add(new Emoji("🇷🇴", "Romania Flag"));
        flags.add(new Emoji("🇷🇺", "Russia Flag"));
        flags.add(new Emoji("🇷🇼", "Rwanda Flag"));
        flags.add(new Emoji("🇼🇸", "Samoa Flag"));
        flags.add(new Emoji("🇸🇲", "San Marino Flag"));
        flags.add(new Emoji("🇸🇹", "Sao Tome & Principe Flag"));
        flags.add(new Emoji("🇸🇦", "Saudi Arabia Flag"));
        flags.add(new Emoji("🇸🇳", "Senegal Flag"));
        flags.add(new Emoji("🇷🇸", "Serbia Flag"));
        flags.add(new Emoji("🇸🇨", "Seychelles Flag"));
        flags.add(new Emoji("🇸🇱", "Sierra Leone Flag"));
        flags.add(new Emoji("🇸🇬", "Singapore Flag"));
        flags.add(new Emoji("🇸🇽", "Sint Maarten Flag"));
        flags.add(new Emoji("🇸🇰", "Slovakia Flag"));
        flags.add(new Emoji("🇸🇮", "Slovenia Flag"));
        flags.add(new Emoji("🇸🇧", "Solomon Islands Flag"));
        flags.add(new Emoji("🇸🇴", "Somalia Flag"));
        flags.add(new Emoji("🇿🇦", "South Africa Flag"));
        flags.add(new Emoji("🇰🇷", "South Korea Flag"));
        flags.add(new Emoji("🇸🇸", "South Sudan Flag"));
        flags.add(new Emoji("🇪🇸", "Spain Flag"));
        flags.add(new Emoji("🇱🇰", "Sri Lanka Flag"));
        flags.add(new Emoji("🇧🇱", "Saint Barthélemy Flag"));
        flags.add(new Emoji("🇸🇭", "Saint Helena Flag"));
        flags.add(new Emoji("🇰🇳", "Saint Kitts & Nevis Flag"));
        flags.add(new Emoji("🇱🇨", "Saint Lucia Flag"));
        flags.add(new Emoji("🇵🇲", "Saint Pierre & Miquelon Flag"));
        flags.add(new Emoji("🇻🇨", "Saint Vincent & Grenadines Flag"));
        flags.add(new Emoji("🇸🇩", "Sudan Flag"));
        flags.add(new Emoji("🇸🇷", "Suriname Flag"));
        flags.add(new Emoji("🇸🇿", "Eswatini Flag"));
        flags.add(new Emoji("🇸🇪", "Sweden Flag"));
        flags.add(new Emoji("🇨🇭", "Switzerland Flag"));
        flags.add(new Emoji("🇸🇾", "Syria Flag"));
        flags.add(new Emoji("🇹🇼", "Taiwan Flag"));
        flags.add(new Emoji("🇹🇯", "Tajikistan Flag"));
        flags.add(new Emoji("🇹🇿", "Tanzania Flag"));
        flags.add(new Emoji("🇹🇭", "Thailand Flag"));
        flags.add(new Emoji("🇹🇱", "Timor-Leste Flag"));
        flags.add(new Emoji("🇹🇬", "Togo Flag"));
        flags.add(new Emoji("🇹🇰", "Tokelau Flag"));
        flags.add(new Emoji("🇹🇴", "Tonga Flag"));
        flags.add(new Emoji("🇹🇹", "Trinidad & Tobago Flag"));
        flags.add(new Emoji("🇹🇳", "Tunisia Flag"));
        flags.add(new Emoji("🇹🇷", "Turkey Flag"));
        flags.add(new Emoji("🇹🇲", "Turkmenistan Flag"));
        flags.add(new Emoji("🇹🇨", "Turks & Caicos Islands Flag"));
        flags.add(new Emoji("🇹🇻", "Tuvalu Flag"));
        flags.add(new Emoji("🇺🇬", "Uganda Flag"));
        flags.add(new Emoji("🇺🇦", "Ukraine Flag"));
        flags.add(new Emoji("🇦🇪", "United Arab Emirates Flag"));
        flags.add(new Emoji("🇬🇧", "United Kingdom Flag"));
        flags.add(new Emoji("🇺🇸", "United States Flag"));
        flags.add(new Emoji("🇺🇾", "Uruguay Flag"));
        flags.add(new Emoji("🇺🇿", "Uzbekistan Flag"));
        flags.add(new Emoji("🇻🇺", "Vanuatu Flag"));
        flags.add(new Emoji("🇻🇦", "Vatican City Flag"));
        flags.add(new Emoji("🇻🇪", "Venezuela Flag"));
        flags.add(new Emoji("🇻🇳", "Vietnam Flag"));
        flags.add(new Emoji("🇼🇫", "Wallis & Futuna Flag"));
        flags.add(new Emoji("🇪🇭", "Western Sahara Flag"));
        flags.add(new Emoji("🇾🇪", "Yemen Flag"));
        flags.add(new Emoji("🇿🇲", "Zambia Flag"));
        flags.add(new Emoji("🇿🇼", "Zimbabwe Flag"));



        blogs.add(new Blog("Title","Description"));
        blogs.add(new Blog("Title2","Description2"));
    }

    @PostConstruct
    public List<Emoji> getAllEmojies(){
        allEmojis.addAll(smilesAndPeople);
        allEmojis.addAll(animalsAndNature);
        allEmojis.addAll(foodAndDrink);
        allEmojis.addAll(travelAndPlaces);
        allEmojis.addAll(activities);
        allEmojis.addAll(objects);
        allEmojis.addAll(symbols);
        allEmojis.addAll(flags);
        return allEmojis;
    }
}
